# config/meta.yml

meta_product_name: "Skrumble"
meta_title: "Skrumble - Adventure begins in your suitcase"
meta_description: "Let us help you prepare your suitcase and arrival in your future destination"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
